### ISSUE TITLE
Downhole points generation attempt returns isValid attribute error

### ISSUE THREAD

**Issue by Coastal0** [rolandhill/geoscience#21]
Attempting to generate downhole points returns the error shown below error. I've attached an example of delocated drillhole collars and survey files which recreate the error.

```
2024-12-10T16:15:46     WARNING    Traceback (most recent call last):
              File "C:\Users/Alexc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\DrillManager.py", line 162, in onDownholePoints
              self.createDownholePoints()
              File "C:\Users/Alexc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\DrillManager.py", line 412, in createDownholePoints
              if not self.desurveyLayer.isValid() or not self.dataLayer.isValid():
              ^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'isValid'
```
[Proposed_Collar_ed_Desurvey.zip](https://github.com/user-attachments/files/18075524/Proposed_Collar_ed_Desurvey.zip)

**Comment by rolandhill** [comment]
Thanks, Alex. I just pushed a fix if you are happy to take it from Github.

Cheers,
Roland
